language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=v2.0.16
    - SYMFONY_VERSION=origin/2.0
    - SYMFONY_VERSION=origin/master

before_script: php bin/vendors.php

script: phpunit

notifications:
    email:
        - noisebleed@noiselabs.org
